AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: EC2Co-EcsEl-1EY9RC78IM3UI-1536900216.us-east-1.elb.amazonaws.com
          Id: mycloudfront
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
        Enabled: 'true'
        DefaultCacheBehavior:
          TargetOriginId: mycloudfront
          ViewerProtocolPolicy: https-only
          AllowedMethods:
          - GET
          - HEAD
          ForwardedValues:
            QueryString: 'false'
          
