AWSTemplateFormatVersion: 2010-09-09

Resources:
  myS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "moviesprojects-3"
 
  moviesAppv1:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: "moviesAppv-1"

  # myAppVersion:
  #   Type: AWS::ElasticBeanstalk::ApplicationVersion
  #   Properties:
  #     ApplicationName:
  #       Ref: "moviesAppv1"
  #     SourceBundle:
  #       S3Bucket:
  #         Fn::Join:
  #           - "-"
  #           - 
  #             - "mahas354"
  #             - "us-east-1"
  #       S3Key: "javabelt-0.0.1-SNAPSHOT.war"
      

  myConfigTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: "moviesAppv-1"
      SolutionStackName: "64bit Amazon Linux 2 v4.2.18 running Tomcat 8.5 Corretto 11"

  enviromant:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: "moviesAppv-1"
      EnvironmentName: "moviesEnvi-1"
      SolutionStackName: "64bit Amazon Linux 2 v4.2.18 running Tomcat 8.5 Corretto 11"
      OptionSettings:
          - Namespace: aws:elasticbeanstalk:environment
            OptionName: EnvironmentType
            Value: LoadBalanced
          - Namespace: aws:autoscaling:launchconfiguration
            OptionName: IamInstanceProfile
            Value: aws-elasticbeanstalk-ec2-role
          - Namespace: aws:elasticbeanstalk:environment
            OptionName: ServiceRole
            Value: aws-elasticbeanstalk-service-role
